spring:
  rabbitmq:
    addresses: 192.168.3.3:5672
    username: admin
    password: 123456
    virtual-host: /
    connection-timeout: 15000
    publisher-confirm-type: simple
    publisher-returns: true
    template:
      mandatory: true